-- MySQL Script generated by MySQL Workbench
-- Tue Jul 25 11:21:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Gym
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Gym
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Gym` DEFAULT CHARACTER SET utf8 ;
USE `Gym` ;

-- -----------------------------------------------------
-- Table `Gym`.`Gym`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gym`.`Gym` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `web` VARCHAR(100) NOT NULL,
  `cp` CHAR(45) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gym`.`Alumn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gym`.`Alumn` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `born_date` DATE NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `cp` VARCHAR(45) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `id_gym` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `gym_alumn_fk_idx` (`id_gym` ASC) VISIBLE,
  CONSTRAINT `gym_alumn_fk`
    FOREIGN KEY (`id_gym`)
    REFERENCES `Gym`.`Gym` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gym`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gym`.`Class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `id_fitness_trainer` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `gym_class_fk_idx` (`id_fitness_trainer` ASC) VISIBLE,
  CONSTRAINT `gym_class_fk`
    FOREIGN KEY (`id_fitness_trainer`)
    REFERENCES `Gym`.`Gym` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gym`.`Firness_trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gym`.`Firness_trainer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `id_gym` INT NOT NULL,
  `id_class` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `gym_fitness_trainer_fk_idx` (`id_gym` ASC) VISIBLE,
  INDEX `fitness_trainer_class_fk_idx` (`id_class` ASC) VISIBLE,
  CONSTRAINT `gym_fitness_trainer_fk`
    FOREIGN KEY (`id_gym`)
    REFERENCES `Gym`.`Gym` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fitness_trainer_class_fk`
    FOREIGN KEY (`id_class`)
    REFERENCES `Gym`.`Class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gym`.`Alumn_has_Firness_trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gym`.`Alumn_has_Firness_trainer` (
  `Alumn_id` INT NOT NULL,
  `Firness_trainer_id` INT NOT NULL,
  PRIMARY KEY (`Alumn_id`, `Firness_trainer_id`),
  INDEX `fk_Alumn_has_Firness_trainer_Firness_trainer1_idx` (`Firness_trainer_id` ASC) VISIBLE,
  INDEX `fk_Alumn_has_Firness_trainer_Alumn1_idx` (`Alumn_id` ASC) VISIBLE,
  CONSTRAINT `fk_Alumn_has_Firness_trainer_Alumn1`
    FOREIGN KEY (`Alumn_id`)
    REFERENCES `Gym`.`Alumn` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumn_has_Firness_trainer_Firness_trainer1`
    FOREIGN KEY (`Firness_trainer_id`)
    REFERENCES `Gym`.`Firness_trainer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gym`.`Alumn_has_Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gym`.`Alumn_has_Class` (
  `Alumn_id` INT NOT NULL,
  `Class_id` INT NOT NULL,
  PRIMARY KEY (`Alumn_id`, `Class_id`),
  INDEX `fk_Alumn_has_Class_Class1_idx` (`Class_id` ASC) VISIBLE,
  INDEX `fk_Alumn_has_Class_Alumn1_idx` (`Alumn_id` ASC) VISIBLE,
  CONSTRAINT `fk_Alumn_has_Class_Alumn1`
    FOREIGN KEY (`Alumn_id`)
    REFERENCES `Gym`.`Alumn` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumn_has_Class_Class1`
    FOREIGN KEY (`Class_id`)
    REFERENCES `Gym`.`Class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
